# 设置tomcat server的启动端口号
server:
  port: 80
  servlet:
    context-path: /admin

spring:
#  加载spring默认的数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/twomeng?&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 970306
#    引入其他的application-xx.yml
  profiles:
    active:
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .html  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式




# mybatis配置
mybatis:
#  实体类别包路径
  type-aliases-package: com.twomeng.modules.sys.domain
  mapper-locations: classpath:/com/twomeng/mapper/sys/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  映射文件路径
